### ISSUE TITLE
remove close window option and modal bug

### ISSUE THREAD

**Issue by jezraelhope** [jezraelhope/wsdb#1]
- remove the close window option (not needed after adding the "click outside the box to close" functionality)
- modal bug (multiple modals open after opening each modal and clicking outside.)

![Image](https://user-images.githubusercontent.com/46736323/214650927-00b79263-dac6-4183-ac2c-9bb77042ff38.png)

**Comment by jezraelhope** [comment]
fixed in commit -  dac984a

**Comment by ash811987** [comment]
verified. Looks good to me.
